[phases.setup]
nixpkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "playwright install chromium"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
